spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tictactoe
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
jwt:
  key: key